In [2]:
import numpy as np


In [10]:
np.array([[1,2,3],[5,6,7]])

array([[1, 2, 3],
       [5, 6, 7]])

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
#bir arrain shape kotnrol etmek için .shape attributesi kullanılır.
#bir arrayin shape i her boyuttaki çğelerinin sayısına eşittir.

In [13]:
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
# 3 satır 4 stünu var arr2d'nin shape'si 3,4 gelir

In [15]:
arr2d.shape

(3, 4)

In [18]:
arr3d = np.array([[ [1,2,3] , [4,5,6]] ,[[10,20,30],[5,12,24] ]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [ 5, 12, 24]]])

In [19]:
# 2,2,3 olur 3 boyutlu bir arrayin shapesi

In [20]:
arr3d.shape

(2, 2, 3)

 #bir array'i reshape(yeniden şekillendirme) etme

In [22]:
#.reshape() methodu arrayin şeklini değişirmeye yarar
#.reshpae yaparken toplam eleman sayısı değişmez dikkat edilmeli


In [23]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [ 5, 12, 24]]])

In [24]:
arr3d.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30,  5, 12, 24]])

In [25]:
arr3d.shape

(2, 2, 3)

In [27]:
arr3dn = np.arange(30).reshape(2,3,5)
arr3dn

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [28]:
#bilinmeyen boyut !
#.reshape boyutu kullanılırken hesaplamak istemediğimiz boyut yerine -1 yazıp otomatik hesaplattırabiliriz.

In [30]:
aar3d = np.arange(120).reshape(5,2,-1)
aar3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23]],

       [[ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47]],

       [[ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71]],

       [[ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95]],

       [[ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]]])

# arrayleri düzleştirmee (flatten)

In [33]:
 #düzleştirme işlemi çok boyutlu bir arrayi 1 boyutlu hale getirme
 # yani bütün verileri tek bir sıra halinde yazma
 # basaitçe .reshape(-1)

In [34]:
ar2d = np.arange(50).reshape(5,10)
ar2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [35]:
ar2d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [37]:
ar34 = np.arange(30).reshape(-1)
ar34

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

# çok boyutlu arraylerde iteration(yineleme)

In [38]:
ars1d = np.arange(10)
ars1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
for i in ars1d:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [40]:
ars2d = np.arange(20).reshape(4,5)
ars2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [41]:
for x in ars2d:
  print(x)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [42]:
for x in ars2d:
    for y in x:
        print(y)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [43]:
ars3d = np.arange(40).reshape(2,2,10)
ars3d

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]])

In [44]:
for x in ars3d:
    for y in x:
        for z in y:
            print(z)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39


In [45]:
#for kullanımı hiçbir şekilde önerilmiyor

#çok boyutlu arraylerde nditer() kullanımı

In [46]:
# for döngüsü arraylerin boyutu kadar sayıda kullanılırsa ancak arrayin bütün elemanlarına tek tek erişebiliriz

In [47]:
# çok boyutlu arraylerde nditer() fonksiyonu bunu için geliştirilmiştir

In [48]:
ars3d

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]])

In [49]:
np.nditer(ars3d)

In [51]:
for x in np.nditer(ars3d):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39


In [52]:
#burda defalarca kez for yazmaya gerek kalmadı.

# array elemanları arasında 4 işlem

In [53]:
ar1 = np.array([1,2,3,4])
ar2 = np.array([5,6,7,8])

In [54]:
ar1 + ar2

array([ 6,  8, 10, 12])

In [55]:
#burda vektörüzasyon şeklinde topama yapar


In [57]:
ar1.__add__(ar2) #magic fonction

array([ 6,  8, 10, 12])

# Bir arrayin toplamına/ortalamasına/varyansına/standart sapmasına bakma

In [61]:
ar1 = np.random.randint(0,10,10)
ar1

array([6, 1, 4, 8, 0, 5, 8, 9, 2, 1])

In [65]:
ar1.sum() #toplama

np.int64(44)

In [66]:
ar1.mean() #ortalama

np.float64(4.4)

In [68]:
ar1.var() #varyansı

np.float64(9.84)

In [69]:
ar1.std() #standart sapma

np.float64(3.1368774282716245)

In [70]:
ar1

array([6, 1, 4, 8, 0, 5, 8, 9, 2, 1])

In [72]:
np.sqrt(ar1)

array([2.44948974, 1.        , 2.        , 2.82842712, 0.        ,
       2.23606798, 2.82842712, 3.        , 1.41421356, 1.        ])

In [73]:
np.sin(ar1)

array([-0.2794155 ,  0.84147098, -0.7568025 ,  0.98935825,  0.        ,
       -0.95892427,  0.98935825,  0.41211849,  0.90929743,  0.84147098])

#numpy arraylerini birleştirme (concatenate)

In [75]:
#numpy arraylerini birleştirme işlemi .concatenate() fonksiyonu ile yapılır

In [76]:
#np.concatenate([ar1,ar2])

In [77]:
ar1 = np.array([1,2,3,4])
ar2 = np.array([5,6,7,8])

In [78]:
np.concatenate([ar1,ar2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
np.concatenate([ar1,ar2],axis=0)
# yan yana ekleme

array([1, 2, 3, 4, 5, 6, 7, 8])

In [80]:
np.concatenate([ar1,ar2],axis=1)
# stün halinde ekleme

AxisError: axis 1 is out of bounds for array of dimension 1

In [81]:
# bir boyutlu arraylerde olmuyor.

In [82]:
ars1 = np.array([[1,2,3],[4,5,6]])
ars2 = np.array([[7,8,9],[10,11,12]])

In [84]:
np.concatenate([ars1,ars2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [85]:
np.concatenate([ars1,ars2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# arrayleri stackleme (yığınlama) işlemleri

In [86]:
# concatenate ile hemen hemen aynı tek farkı yeni bir boyut üzerinde yığınlama yapar

In [87]:
np.stack([ar1,ar2],axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [89]:
np.stack([ar1,ar2],axis=1) #fazladan 1 boyut ekliyor []

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [90]:
#np.hstack() satır boyunca yığınlama
#np.vstack() stün boyunca yığınlama

# numpy arraylerinde arama

In [91]:
#aradığımız değerlerin bulunduğu indexleri döndürmek için
#np.where() fonksiyonu kullanılır içine condition alır(şart)

In [94]:
arz1 = np.array([1,2,3,4,44,3,52,1,12,2,2,2])

In [98]:
np.where(arz1 == 2) #arrayde bulunan kaçıncı indexler 2 dir bunu gösterir.

(array([ 1,  9, 10, 11]),)

# numpy random kütüphanesi

In [99]:
#random kütühanesi normalde olmasının yanında numpy içersinde ayrı bir random bulunur
# normal random kütüphanesinde daha kapsamlıdır

In [100]:
import numpy as np


In [102]:
np.random.randint(1)

0

In [104]:
np.random.choice(arz1) #random sayı çeker

np.int64(52)

In [105]:
#done.