In [1]:
#numpy açık kaynak python kütühanesidir
#sayılarla işlem yapmayı hızlandırır matematiksel işlemler
#numpy kütühanesinin en temel elemanı array(dizi)
#arraylerin python dizilerinin çok boyutlu olanı.^
#arrayler listlerden 50 kat daha hızlı çalışır.
#numpy arraylerinin hızlı çalışmasının nedeni c ve c++ ile yazılmış olmaısıdır.


NumPy Yüklenmesi


In [2]:
#collab kullanırken numpy zaten kurulu.

NumPy'ı projeye dahil etme

In [3]:
import numpy as np


Numpy arrayleri oluşturma


In [4]:
#arrayler çok boyutlu diziler olarak düşünebiliriz
# arraylerin boyutları vardır 1d,2d,3d...

#arrayleri oluşturmanın 3 yolu
#1)liste ya da tuple benzeri nesneleri array e dönüştürebiliriz
#np.array(1,2,3):
#2 build in hazır fonksiyonlar yardımıyla oluşturabiliriz np.arange() gibi vs
#3 rastgele data üreterek oluşturabiliriz np.random() ile


In [8]:
# 0 boyutlu array
ar0d = np.array(53)
ar0d

array(53)

In [12]:
# 1 boyutlu array
ar1d = np.array([1,2,3,4])
ar1d

array([1, 2, 3, 4])

In [14]:
# 2 boyutlu array
ar2d = np.array([[1,2,3],[4,5,6]])
ar2d

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# 3 boyutlu array
ar3d = np.array([[[1,2,3],[4,5,6],[7,8,9],[100,200,300]]])
ar3d

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9],
        [100, 200, 300]]])

In [16]:
# 2 boyutlu başka bir array
array20 = np.array([[1,5,6],[7,0,6]])
array20

array([[1, 5, 6],
       [7, 0, 6]])

#Built-in fonksiyonlarla hızlıca numpy arrayleri oluşturma


In [ ]:
#np.arange() fonksiyonu ile hızlıca arrayler oluşturabiliriz.
#istediğimiz sayı aralığında ardışık artan arrayler.
#kulllanımı aynen range() gibi start point dahil end point dahil değil.
#start stop end parametrelerini alır.

In [17]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(30,100,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96,
       98])

In [ ]:
#nm.linspace() fonksiyonuyla da hızlıca arrayler oluşturulabilir.

In [23]:
np.linspace(1,10,5)
# 1 ile 10 arası 5 tane veri döndürür.

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [29]:
np.logspace(1,3,7) # 10 ^ 1 ile 3 arasında 7 tane veriden oluşan bir array oluştur.
#logaritmik artış ile oluşturur,aynı mantık.

array([  10.        ,   21.5443469 ,   46.41588834,  100.        ,
        215.443469  ,  464.15888336, 1000.        ])

In [31]:
np.arange(10,105,5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [32]:
np.linspace(0,1000,26)

array([   0.,   40.,   80.,  120.,  160.,  200.,  240.,  280.,  320.,
        360.,  400.,  440.,  480.,  520.,  560.,  600.,  640.,  680.,
        720.,  760.,  800.,  840.,  880.,  920.,  960., 1000.])

In [33]:
np.zeros(5) #sıfırladan oluşan 5 elemanlı array

array([0., 0., 0., 0., 0.])

In [36]:
np.zeros((2,3),dtype=int) # 2 boyutlu 3 stün array.

array([[0, 0, 0],
       [0, 0, 0]])

In [37]:
np.ones(10) #birlerden oluşan array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
np.eye(5) #5x5 biri matris oluştur

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.zeros([2,6], dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
#np.random modülünü kullanrak rastgele verilerle arrayler oluşturmak

In [45]:
np.random.rand(2) # 0-1 aralığında oluşturur.

array([0.69556598, 0.24227767])

In [47]:
np.random.rand(2,5)

array([[0.53908487, 0.42050529, 0.07864494, 0.08227457, 0.96397174],
       [0.27290506, 0.94862347, 0.06091791, 0.92634728, 0.49052318]])

In [48]:
np.random.randint(15,50,5)
 #random integer parametreler alır
 #15 ile 50 arası 5 sayı oluşturur.

array([47, 31, 31, 30, 45])

In [49]:
np.random.randint(0,100,(3,3))
 #0 ile 100 arası 3 satır 3 stündan oluşan integer veriler


array([[62, 72, 33],
       [78, 26,  7],
       [55, 78, 83]])

In [50]:
 np.random.randint(0,50,(4,6))

array([[ 3, 30, 20,  3, 13, 22],
       [13, 45, 14,  0, 37, 35],
       [33, 33,  1, 26, 21, 41],
       [28,  5, 16, 10, 20, 38]])

#Bir arrayın boyut sayısını ve shape kontrol etmek

In [51]:
ar0d

array(53)

In [52]:
ar1d

array([1, 2, 3, 4])

In [53]:
ar2d

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
ar3d

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9],
        [100, 200, 300]]])

In [55]:
# ndim attributesi ile arrayimizin boyutuna bakabiliriz.

In [56]:
ar0d.ndim

0

In [57]:
ar1d.ndim

1

In [58]:
ar2d.ndim

2

In [59]:
ar3d

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9],
        [100, 200, 300]]])

In [60]:
ar2d

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
#.shape attributesi ile arrayin shapeine erişilir

In [62]:
ar2d.shape

(2, 3)

In [64]:
ar3d.shape #ilki adet ikincisi stün üçüncüsü stün

(1, 4, 3)

#numpy arraylerini indexleme ve öğelere erişme

In [66]:
ar1d #1 boyutlu arrayler aynı listeler gibidir

array([1, 2, 3, 4])

In [67]:
ar1d[3]

np.int64(4)

In [68]:
ar2d

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
ar2d[0]

array([1, 2, 3])

In [70]:
ar3d

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9],
        [100, 200, 300]]])

In [75]:
ar3d[0,2,2]

np.int64(9)

In [85]:
ara1 = np.arange(53,62)
ara1

array([53, 54, 55, 56, 57, 58, 59, 60, 61])

In [86]:
ara1[4]

np.int64(57)

#numpy dizilerinin max-min elemanlarına ve indexlerine erişme

In [89]:
array01 = np.random.randint(1,100,10)
array01

array([18, 47, 47, 86, 91, 49, 59, 41, 31, 20])

In [90]:
array01.max()

np.int64(91)

In [91]:
array01.min()

np.int64(18)

In [93]:
array01.argmax()
#arrayde bulunan max değerin indexi

np.int64(4)

In [95]:
array01.argmin()
#arrayde bulunan minimum değerin indexi

np.int64(0)

#numpy arraylerinde slicing (dilimleme)

In [98]:
arama = np.arange(50,65)
arama

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [101]:
arama[5:11] #5. index ile 10. index alma

array([55, 56, 57, 58, 59, 60])

In [102]:
arama[-5:]

array([60, 61, 62, 63, 64])

In [103]:
arama[0:10:2]

array([50, 52, 54, 56, 58])

In [105]:
arama[0:2] = 999 #broadcasting
arama

array([999, 999,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64])

In [108]:
arama2 = np.arange(-30,10)

In [110]:
arama2[5:19]

array([-25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13,
       -12])

#bir array data type kontrol etme

In [111]:
#.dtype attribute ile data typesi kontrol edilir

In [113]:
last = np.arange(0,9)

In [114]:
last.dtype

dtype('int64')

In [117]:
last2 = np.arange(50, dtype = "float")
last2

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [120]:
last3 = np.array(["a","b","c"])
last3

array(['a', 'b', 'c'], dtype='<U1')

#Bir array'ın dtype'nı değiştirme

In [122]:
last4 = np.array([2.3,4.2,5.23])
last4

array([2.3 , 4.2 , 5.23])

In [123]:
#.astype methodu ile dtype değiştirilebilir

In [126]:
last4 = last4.astype("int")
last4

array([2, 4, 5])